In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import json

In [191]:
excel_data = pd.read_excel('all_players.xlsx')
print(excel_data['name'][1])
type(excel_data['id'][1])

Virender Sehwag

numpy.int64

In [114]:
batting_stats = open('test_batting_stats.xlsx', 'w')

In [115]:
headers = ["Name","M","Inn","NO","Runs","HS","Avg","BF","SR","100","200","50","4s","6s"]

In [116]:
df = pd.DataFrame(columns=headers)

In [199]:
url = "https://www.cricbuzz.com/profiles/378"

response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

In [200]:
table = soup.find('table', class_='table cb-col-100 cb-plyr-thead')

rows = table.find_all('tr')

data = []

a = [[]]

In [201]:
flag = False
for row in rows:
    i=0
    if flag==True:
        break
    
    row_data = []
    cells = row.find_all('td')
    for cell in cells:
        if cell.text == 'Test': 
            row_data.append(excel_data['name'][i])
            flag = True
            i+=1
        else:
            row_data.append(cell.text)
    if row_data:  # Skip header row and empty rows
        data.append(row_data)

In [202]:
json_data = {
    'values': data
}


# json_data = json.dumps(table_data, indent=4)

# Print or save the JSON data as per your requirement
print(json_data)

{'values': [['Sachin Tendulkar', '37', '57', '5', '407', '36', '7.83', '1141', '35.67', '0', '0', '0', '50', '4']]}

In [177]:
values = json_data['values'][0]
a.append(values)
a=a[1:]
# stats = pd.DataFrame(values)
# stats1 = pd.DataFrame(values)
# a = pd.concat([stats1, stats])
print(values)
print(type(values))
print(a)

['Sachin Tendulkar', '164', '286', '32', '13288', '270', '52.31', '31258', '42.51', '36', '5', '63', '1655', '21']
<class 'list'>
[['Sachin Tendulkar', '164', '286', '32', '13288', '270', '52.31', '31258', '42.51', '36', '5', '63', '1655', '21'], ['Sachin Tendulkar', '164', '286', '32', '13288', '270', '52.31', '31258', '42.51', '36', '5', '63', '1655', '21'], ['Sachin Tendulkar', '164', '286', '32', '13288', '270', '52.31', '31258', '42.51', '36', '5', '63', '1655', '21']]

In [178]:
x = pd.DataFrame(a, columns=headers)
x

,Name,M,Inn,NO,Runs,HS,Avg,BF,SR,100,200,50,4s,6s
0,Sachin Tendulkar,164,286,32,13288,270,52.31,31258,42.51,36,5,63,1655,21
1,Sachin Tendulkar,164,286,32,13288,270,52.31,31258,42.51,36,5,63,1655,21
2,Sachin Tendulkar,164,286,32,13288,270,52.31,31258,42.51,36,5,63,1655,21

In [203]:
excel_data = pd.read_excel('all_players.xlsx')
batting_stats = open('test_batting_stats.xlsx', 'w')
headers = ["Name","M","Inn","NO","Runs","HS","Avg","BF","SR","100","200","50","4s","6s"]

stats_dataframe = []
df = pd.DataFrame(columns=headers)
stats = [[]]
i=0
for id in excel_data['id']:
    url = "https://www.cricbuzz.com/profiles/"+str(id)

    response = requests.get(url)

    soup = BeautifulSoup(response.text, 'html.parser')

    table = soup.find('table', class_='table cb-col-100 cb-plyr-thead')

    if table is not None:

        rows = table.find_all('tr')
        print(i)
        data = []

        flag = False
        for row in rows:

            if flag==True:
                break
            
            row_data = []
            cells = row.find_all('td')
            for cell in cells:
                if cell.text == 'Test': 
                    row_data.append(excel_data['name'][i])
                    flag = True
                   
                else:
                    row_data.append(cell.text)
                i+=1   
            if row_data:  # Skip header row and empty rows
                data.append(row_data)

        json_data = {
            'values': data
        }

        values = json_data['values'][0]
        stats.append(values)
    
    else:
        print("Table not found for id:", id)

stats = stats[1:]
batting_stats_table = pd.DataFrame(stats, columns=headers)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
40
40
40
41
42
43
44
45
46
47
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
84
85
86
87
88
89
90
90
91
92
93
94
95
96
97
97
97
97
97
97
97
97
97
97
97
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
129
130
131
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
152
153
154
155
156
157
158
159
160
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
187
188
189
Table not found for id: 408
190
190
191
192
192
193
194
195
196
197
198
199
200
200
201
202
203
204
205
206
207
208
208
209
210
211
212
212
213
214
215
216
216
217
218
218
219
220
221
221
222
223
224
225
226
227
227
228
229
230
230
230
231
232
233
234
235
236
237
238
238
239
240
241
242
243
244
244
244
245
245
245
245
246
247
248
249
249
249
250
250
250
250
251
251
251
251
252
252
252
252
252
252
253
254
254
255
256
256
257
258
258
258
259
259
260
261
262
263
264
264
Table not found for id: 581
264
265
266
267
268
268
269
269
270
271
272
272
273
274
275
276
276
277
277
277
278
279
279
279
279
279
279
279
279
279
279
279
280
281
282
282
282
282
282
282
282
282
282
282
282
282
282
282
282
282

KeyboardInterrupt:

In [205]:
batting_stats_table

,Name,M,Inn,NO,Runs,HS,Avg,BF,SR,100,200,50,4s,6s
0,Sachin Tendulkar,200,329,33,15921,248,53.79,29437,54.08,51,6,68,2058,69
1,Virender Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,6,32,1233,91
2,Rahul Dravid,164,286,32,13288,270,52.31,31258,42.51,36,5,63,1655,21
3,VVS Laxman,134,225,32,8781,281,45.5,17785,49.37,17,2,56,1135,5
4,Sourav Ganguly,113,188,17,7212,239,42.18,14070,51.26,16,1,35,900,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,ODI,15,11,5,180,44,30.0,272,66.18,0,0,0,8,2
369,ODI,41,40,3,1102,98,29.78,1615,68.24,0,0,10,105,6
370,ODI,33,32,9,1541,119,67.0,1757,87.71,5,0,9,130,29
371,ODI,37,31,1,633,80,21.1,953,66.42,0,0,3,57,15
372,ODI,20,18,3,240,37,16.0,351,68.38,0,0,0,15,4

In [204]:
stats = stats[1:]
batting_stats_table = pd.DataFrame(stats, columns=headers)