In [55]:
import requests
import pandas as pd

url = "https://unofficial-cricbuzz.p.rapidapi.com/players/get-batting"

id=28

dfs = []
responses = []

headers = {
	"X-RapidAPI-Key": "7342f3af94msh458c6999db3a295p1672a0jsn1d4f7254e3ca",
	"X-RapidAPI-Host": "unofficial-cricbuzz.p.rapidapi.com",
    "access-control-allow-origin": "*"  
}
for i in range(2):
    querystring = {"playerId":id}
    response = requests.get(url, headers=headers, params=querystring)
    id+=1
    data = response.json()
    responses.append(data)
responses
    # df = pd.DataFrame(data)
    # print(data)
    # print(data['values'][0]['values'][1])
    # print(response.json())

[{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '134', '86', '0', '20']},
   {'values': ['Innings', '225', '83', '0', '20']},
   {'values': ['Runs', '8781', '2338', '0', '282']},
   {'values': ['Balls', '17785', '3282', '0', '267']},
   {'values': ['Highest', '281', '131', '0', '52']},
   {'values': ['Average', '45.5', '30.76', '0', '14.84']},
   {'values': ['SR', '49.37', '71.24', '0', '105.62']},
   {'values': ['Not Out', '32', '7', '0', '1']},
   {'values': ['Fours', '1135', '222', '0', '33']},
   {'values': ['Sixes', '5', '4', '0', '5']},
   {'values': ['Ducks', '15', '3', '0', '4']},
   {'values': ['50s', '56', '10', '0', '1']},
   {'values': ['100s', '17', '6', '0', '0']},
   {'values': ['200s', '2', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'VVS Laxman Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/28/vvs-laxman'},
  'seriesSpinner': [{'seriesName': 'Career'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '113', '311', '0', '59']},
   {'values': ['Innings', '188', '300', '0', '56']},
   {'values': ['Runs', '7212', '11363', '0', '1349']},
   {'values': ['Balls', '14070', '15416', '0', '1263']},
   {'values': ['Highest', '239', '183', '0', '91']},
   {'values': ['Average', '42.18', '40.73', '0', '25.45']},
   {'values': ['SR', '51.26', '73.71', '0', '106.81']},
   {'values': ['Not Out', '17', '21', '0', '3']},
   {'values': ['Fours', '900', '1122', '0', '137']},
   {'values': ['Sixes', '57', '190', '0', '42']},
   {'values': ['Ducks', '13', '16', '0', '4']},
   {'values': ['50s', '35', '72', '0', '7']},
   {'values': ['100s', '16', '22', '0', '0']},
   {'values': ['200s', '1', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Sourav Ganguly Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/29/sourav-ganguly'},
  'seriesSpinner': [{'seriesName': 'Career'}]}]

In [54]:
for response in responses:  
    headers = response['headers']
    values = [item['values'] for item in response['values']]
    df = pd.DataFrame(values, columns=headers)
    dfs.append(df)
combined_df = pd.concat(dfs, ignore_index=True)

combined_df

   ROWHEADER   Test    ODI T20     IPL
0    Matches    134     86   0      20
1    Innings    225     83   0      20
2       Runs   8781   2338   0     282
3      Balls  17785   3282   0     267
4    Highest    281    131   0      52
5    Average   45.5  30.76   0   14.84
6         SR  49.37  71.24   0  105.62
7    Not Out     32      7   0       1
8      Fours   1135    222   0      33
9      Sixes      5      4   0       5
10     Ducks     15      3   0       4
11       50s     56     10   0       1
12      100s     17      6   0       0
13      200s      2      0   0       0
14      300s      0      0   0       0
15      400s      0      0   0       0
16   Matches    113    311   0      59
17   Innings    188    300   0      56
18      Runs   7212  11363   0    1349
19     Balls  14070  15416   0    1263
20   Highest    239    183   0      91
21   Average  42.18  40.73   0   25.45
22        SR  51.26  73.71   0  106.81
23   Not Out     17     21   0       3
24     Fours    900   1122   0     137
25     Sixes     57    190   0      42
26     Ducks     13     16   0       4
27       50s     35     72   0       7
28      100s     16     22   0       0
29      200s      1      0   0       0
30      300s      0      0   0       0
31      400s      0      0   0       0